apiVersion: opa.stackable.tech/v1
kind: RegoRule
metadata:
  name: simple
spec:
  rego: |
    package kafka.authz

    default allow = false

    allow {
      not deny
    }

    deny {
      not is_minute_even
    }

    is_minute_even {
      floor(time.now_ns() / (1000 * 1000 * 1000 * 60)) % 2 == 0
    }